### ISSUE TITLE
Getting error when trying to run project using Expo start....

### ISSUE THREAD

**Issue by nayan2** [hkxicor/uber-clone-react-native#4]
I have followed all the necessary steps u told in your repo/project. I had restored all the packages. and then also run the command npm link. after doing all the stay when i tried to run the project using expo start / expo build:android .... i am getting error like ....

[12:57:08] Starting project at F:\React native\uber-clone-react-native
[12:57:09] Expo DevTools is running at http://localhost:19002
[12:57:09] Opening DevTools in the browser... (press shift-d to disable)
**[12:57:18] (node:23568) UnhandledPromiseRejectionWarning: Error: Cannot find module 'F:\React native\uber-clone-react-native\node_modules\expo\tools\LogReporter'
[12:57:18]     at Function.Module._resolveFilename (module.js:547:15)
[12:57:18]     at Function.Module._load (module.js:474:25)
[12:57:18]     at Module.require (module.js:596:17)
[12:57:18]     at require (internal/module.js:11:18)
[12:57:18]     at getReporterImpl (F:\React native\uber-clone-react-native\node_modules\react-native\local-cli\server\runServer.js:120:12)
[12:57:18]     at runServer (F:\React native\uber-clone-react-native\node_modules\react-native\local-cli\server\runServer.js:50:24)
[12:57:18]     at Object.server [as func] (F:\React native\uber-clone-react-native\node_modules\react-native\local-cli\server\server.js:26:3)
[12:57:18]     at Promise.resolve.then (F:\React native\uber-clone-react-native\node_modules\react-native\local-cli\cliEntry.js:117:22)
[12:57:18]     at <anonymous>
[12:57:18] (node:23568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[12:57:18] (node:23568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12:57:18] Metro Bundler process exited with code 0
[12:57:18] Set EXPO_DEBUG=true in your env to view the stack trace.**

pls help me to solve the problem.....

**Comment by hkxicor** [comment]
This project is not build using expo. you have to simply use
`react-native run-ios `
or
`react-native run-android`
